---

language: android

sudo: false

android:
  components:
    - android-22
    - build-tools-22.0.1

install:
  - npm install -g coffee-script
  - cake install

script:
  - cd src && npm run test && cd ..
  - cd src && npm run lint && cd ..
  - ./src/node_modules/.bin/cordova build android
