---

language: android

sudo: false

android:
  components:
    - build-tools-22.0.1

install:
  - npm install -g cordova@4.3.1
  - cd www-src && npm install
  - export PATH=$PATH:$PWD/www-src/node_modules/.bin
  - cake platforms && cake plugins

script:
  - npm test
