---

language: android

sudo: false

jdk:
  - oraclejdk8

env:
  - TRAVIS_NODE_VERSION="4"

android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # to install Android SDK tools 25.1.x (x = 6 right now)
    - build-tools-24.0.1
    - android-24

install:
  - nvm install $TRAVIS_NODE_VERSION
  - cd src && npm install && cd ..

script:
  - cd src && npm run lint && cd ..
  - cd src && npm run test:coverage && cd ..
  - ./src/node_modules/.bin/cordova build android

after_success:
  - ./src/node_modules/.bin/codecov
