---

language: android

sudo: false

jdk:
  - oraclejdk8

env:
  - TRAVIS_NODE_VERSION="6.9.1"

android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # to install Android SDK tools 25.1.x (x = 6 right now)
    - build-tools-25.0.0
    - android-25

cache:
  directories:
    - node_modules
    - platforms
    - plugins

install:
  - nvm install $TRAVIS_NODE_VERSION
  - npm install

script:
  - npm run lint
  - npm run test:coverage
  - ./node_modules/.bin/cordova build android

after_success:
  - ./node_modules/.bin/codecov
